# Publish a -beta version to npm

name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        id: node
        uses: actions/setup-node@v2
        env:
          PLAYER_NPM_PUBLISH: ${{ secrets.PLAYER_NPM_PUBLISH }}
        with:
          node-version: '16'
          cache: 'npm'

      - name: Publish npm package
        env:
          PLAYER_NPM_PUBLISH: ${{ secrets.PLAYER_NPM_PUBLISH }}
        working-directory: package
        run: |
          npm --version
          echo '_authToken=${PLAYER_NPM_PUBLISH}' > .npmrc
          npm publish --tag beta
          rm .npmrc
